/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects.$projectId'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as ApiMediaUploadRouteImport } from './routes/api/media/upload'
import { Route as ApiPublicScreenshotRouteImport } from './routes/api/public/screenshot'
import { Route as ApiPublicCompositionExportsExportIdRouteImport } from './routes/api/public/composition-exports.$exportId'
import { Route as ApiPublicDemoRecordingsDemoIdRouteImport } from './routes/api/public/demo-recordings.$demoId'
import { Route as ApiPublicEvidenceFileIdRouteImport } from './routes/api/public/evidence.$fileId'
import { Route as ApiPublicMediaAssetIdRouteImport } from './routes/api/public/media.$assetId'
import { Route as ApiPublicVideoRendersRenderIdRouteImport } from './routes/api/public/video-renders.$renderId'
import { Route as ProjectsProjectIdDemosDemoIdEditorRouteImport } from './routes/projects.$projectId_.demos.$demoId.editor'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiMediaUploadRoute = ApiMediaUploadRouteImport.update({
  id: '/api/media/upload',
  path: '/api/media/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicScreenshotRoute = ApiPublicScreenshotRouteImport.update({
  id: '/api/public/screenshot',
  path: '/api/public/screenshot',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCompositionExportsExportIdRoute =
  ApiPublicCompositionExportsExportIdRouteImport.update({
    id: '/api/public/composition-exports/$exportId',
    path: '/api/public/composition-exports/$exportId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicDemoRecordingsDemoIdRoute =
  ApiPublicDemoRecordingsDemoIdRouteImport.update({
    id: '/api/public/demo-recordings/$demoId',
    path: '/api/public/demo-recordings/$demoId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicEvidenceFileIdRoute = ApiPublicEvidenceFileIdRouteImport.update({
  id: '/api/public/evidence/$fileId',
  path: '/api/public/evidence/$fileId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMediaAssetIdRoute = ApiPublicMediaAssetIdRouteImport.update({
  id: '/api/public/media/$assetId',
  path: '/api/public/media/$assetId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicVideoRendersRenderIdRoute =
  ApiPublicVideoRendersRenderIdRouteImport.update({
    id: '/api/public/video-renders/$renderId',
    path: '/api/public/video-renders/$renderId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectsProjectIdDemosDemoIdEditorRoute =
  ProjectsProjectIdDemosDemoIdEditorRouteImport.update({
    id: '/projects/$projectId_/demos/$demoId/editor',
    path: '/projects/$projectId/demos/$demoId/editor',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/media/upload': typeof ApiMediaUploadRoute
  '/api/public/screenshot': typeof ApiPublicScreenshotRoute
  '/api/public/composition-exports/$exportId': typeof ApiPublicCompositionExportsExportIdRoute
  '/api/public/demo-recordings/$demoId': typeof ApiPublicDemoRecordingsDemoIdRoute
  '/api/public/evidence/$fileId': typeof ApiPublicEvidenceFileIdRoute
  '/api/public/media/$assetId': typeof ApiPublicMediaAssetIdRoute
  '/api/public/video-renders/$renderId': typeof ApiPublicVideoRendersRenderIdRoute
  '/projects/$projectId/demos/$demoId/editor': typeof ProjectsProjectIdDemosDemoIdEditorRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/media/upload': typeof ApiMediaUploadRoute
  '/api/public/screenshot': typeof ApiPublicScreenshotRoute
  '/api/public/composition-exports/$exportId': typeof ApiPublicCompositionExportsExportIdRoute
  '/api/public/demo-recordings/$demoId': typeof ApiPublicDemoRecordingsDemoIdRoute
  '/api/public/evidence/$fileId': typeof ApiPublicEvidenceFileIdRoute
  '/api/public/media/$assetId': typeof ApiPublicMediaAssetIdRoute
  '/api/public/video-renders/$renderId': typeof ApiPublicVideoRendersRenderIdRoute
  '/projects/$projectId/demos/$demoId/editor': typeof ProjectsProjectIdDemosDemoIdEditorRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/media/upload': typeof ApiMediaUploadRoute
  '/api/public/screenshot': typeof ApiPublicScreenshotRoute
  '/api/public/composition-exports/$exportId': typeof ApiPublicCompositionExportsExportIdRoute
  '/api/public/demo-recordings/$demoId': typeof ApiPublicDemoRecordingsDemoIdRoute
  '/api/public/evidence/$fileId': typeof ApiPublicEvidenceFileIdRoute
  '/api/public/media/$assetId': typeof ApiPublicMediaAssetIdRoute
  '/api/public/video-renders/$renderId': typeof ApiPublicVideoRendersRenderIdRoute
  '/projects/$projectId_/demos/$demoId/editor': typeof ProjectsProjectIdDemosDemoIdEditorRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/projects/$projectId'
    | '/.mcp/invoke-tool/$tool'
    | '/api/media/upload'
    | '/api/public/screenshot'
    | '/api/public/composition-exports/$exportId'
    | '/api/public/demo-recordings/$demoId'
    | '/api/public/evidence/$fileId'
    | '/api/public/media/$assetId'
    | '/api/public/video-renders/$renderId'
    | '/projects/$projectId/demos/$demoId/editor'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/projects/$projectId'
    | '/.mcp/invoke-tool/$tool'
    | '/api/media/upload'
    | '/api/public/screenshot'
    | '/api/public/composition-exports/$exportId'
    | '/api/public/demo-recordings/$demoId'
    | '/api/public/evidence/$fileId'
    | '/api/public/media/$assetId'
    | '/api/public/video-renders/$renderId'
    | '/projects/$projectId/demos/$demoId/editor'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/projects/$projectId'
    | '/.mcp/invoke-tool/$tool'
    | '/api/media/upload'
    | '/api/public/screenshot'
    | '/api/public/composition-exports/$exportId'
    | '/api/public/demo-recordings/$demoId'
    | '/api/public/evidence/$fileId'
    | '/api/public/media/$assetId'
    | '/api/public/video-renders/$renderId'
    | '/projects/$projectId_/demos/$demoId/editor'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  McpRoute: typeof McpRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiMediaUploadRoute: typeof ApiMediaUploadRoute
  ApiPublicScreenshotRoute: typeof ApiPublicScreenshotRoute
  ApiPublicCompositionExportsExportIdRoute: typeof ApiPublicCompositionExportsExportIdRoute
  ApiPublicDemoRecordingsDemoIdRoute: typeof ApiPublicDemoRecordingsDemoIdRoute
  ApiPublicEvidenceFileIdRoute: typeof ApiPublicEvidenceFileIdRoute
  ApiPublicMediaAssetIdRoute: typeof ApiPublicMediaAssetIdRoute
  ApiPublicVideoRendersRenderIdRoute: typeof ApiPublicVideoRendersRenderIdRoute
  ProjectsProjectIdDemosDemoIdEditorRoute: typeof ProjectsProjectIdDemosDemoIdEditorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/media/upload': {
      id: '/api/media/upload'
      path: '/api/media/upload'
      fullPath: '/api/media/upload'
      preLoaderRoute: typeof ApiMediaUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/screenshot': {
      id: '/api/public/screenshot'
      path: '/api/public/screenshot'
      fullPath: '/api/public/screenshot'
      preLoaderRoute: typeof ApiPublicScreenshotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/composition-exports/$exportId': {
      id: '/api/public/composition-exports/$exportId'
      path: '/api/public/composition-exports/$exportId'
      fullPath: '/api/public/composition-exports/$exportId'
      preLoaderRoute: typeof ApiPublicCompositionExportsExportIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/demo-recordings/$demoId': {
      id: '/api/public/demo-recordings/$demoId'
      path: '/api/public/demo-recordings/$demoId'
      fullPath: '/api/public/demo-recordings/$demoId'
      preLoaderRoute: typeof ApiPublicDemoRecordingsDemoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/evidence/$fileId': {
      id: '/api/public/evidence/$fileId'
      path: '/api/public/evidence/$fileId'
      fullPath: '/api/public/evidence/$fileId'
      preLoaderRoute: typeof ApiPublicEvidenceFileIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/media/$assetId': {
      id: '/api/public/media/$assetId'
      path: '/api/public/media/$assetId'
      fullPath: '/api/public/media/$assetId'
      preLoaderRoute: typeof ApiPublicMediaAssetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/video-renders/$renderId': {
      id: '/api/public/video-renders/$renderId'
      path: '/api/public/video-renders/$renderId'
      fullPath: '/api/public/video-renders/$renderId'
      preLoaderRoute: typeof ApiPublicVideoRendersRenderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId_/demos/$demoId/editor': {
      id: '/projects/$projectId_/demos/$demoId/editor'
      path: '/projects/$projectId/demos/$demoId/editor'
      fullPath: '/projects/$projectId/demos/$demoId/editor'
      preLoaderRoute: typeof ProjectsProjectIdDemosDemoIdEditorRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  McpRoute: McpRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  ProjectsProjectIdRoute: ProjectsProjectIdRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiMediaUploadRoute: ApiMediaUploadRoute,
  ApiPublicScreenshotRoute: ApiPublicScreenshotRoute,
  ApiPublicCompositionExportsExportIdRoute:
    ApiPublicCompositionExportsExportIdRoute,
  ApiPublicDemoRecordingsDemoIdRoute: ApiPublicDemoRecordingsDemoIdRoute,
  ApiPublicEvidenceFileIdRoute: ApiPublicEvidenceFileIdRoute,
  ApiPublicMediaAssetIdRoute: ApiPublicMediaAssetIdRoute,
  ApiPublicVideoRendersRenderIdRoute: ApiPublicVideoRendersRenderIdRoute,
  ProjectsProjectIdDemosDemoIdEditorRoute:
    ProjectsProjectIdDemosDemoIdEditorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
